#
# Makefile
#

CIRCLEHOME = ../Circle

INCLUDE	+= -I ./include
INCLUDE	+= -I ../lib-properties/include
INCLUDE	+= -I ../include

OBJS	= src/rpi_circle.o src/networkparams.o

EXTRACLEAN = src/*.o

libnetwork.a: $(OBJS)
	rm -f $@
	$(AR) cr $@ $(OBJS)
	$(PREFIX)objdump -D libnetwork.a | $(PREFIX)c++filt > libnetwork.lst

include $(CIRCLEHOME)/Rules.mk
