#
DEFINES = NDEBUG
#
EXTRA_INCLUDES = ../lib-properties/include ../lib-esp8266/include ../lib-wiznet ../lib-wiznet/ioLibrary_Driver/Ethernet  ../lib-utils/include
#
include ../h3-firmware-template/lib/Rules.mk
