DEFINES=NDEBUG

EXTRA_INCLUDES=

EXTRA_SRCDIR=src/net/apps/tftp

ifeq ($(findstring CONFIG_NETWORK_USE_MINIMUM,$(MAKE_FLAGS)), CONFIG_NETWORK_USE_MINIMUM)
else
	EXTRA_SRCDIR+=src/net/apps/mdns src/params
endif

include ../firmware-template-linux/lib/Rules.mk
