#
DEFINES = NDEBUG
#
EXTRA_INCLUDES =  ../lib-artnet/include ../lib-artnet4/include ../lib-display/include ../lib-displayudf/include ../lib-e131/include ../lib-lightset/include ../lib-network/include ../lib-spiflashstore/include
#
include ../h3-firmware-template/lib/Rules.mk
