DEFINES=RDM_CONTROLLER UPDATE_CONFIG_FILE DISABLE_RTC ENABLE_MMU NDEBUG

LIBS=widget dmx rdm usb network display hal

SRCDIR=firmware

EXTRA_INCLUDES=

include ../firmware-template-bcm/Rules.mk

prerequisites:
