#
DEFINES = RDM_CONTROLLER UPDATE_CONFIG_FILE ENABLE_MMU NDEBUG
#
LIBS = widget dmx rdm usb
#
SRCDIR = firmware oled oled/i2c
#
EXTRA_INCLUDES = 

include ../firmware-template/Rules.mk

prerequisites:
