#
DEFINES = RDM_CONTROLLER UPDATE_CONFIG_FILE ENABLE_MMU NDEBUG
#
LIBS = dmx monitor
#
SRCDIR = firmware lib
#
EXTRA_INCLUDES = ../lib-ff11/src

include ../firmware-template/Rules.mk

prerequisites:
	./generate_sofware_version_id.sh	