DEFINES =NODE_ARTNET ARTNET_VERSION=3 LIGHTSET_PORTS=4 

DEFINES+=ESP8266 
DEFINES+=CONSOLE_FB 
DEFINES+=ENABLE_MMU 

DEFINES+=DISABLE_RTC 

DEFINES+=NDEBUG

LIBS=display artnet dmxmonitor dmx lightset

SRCDIR=firmware lib

include ../firmware-template-bcm/Rules.mk

prerequisites: