PLATFORM=ORANGE_PI

DEFINES=NODE_OSC_SERVER
DEFINES+=OUTPUT_DMX_PIXEL
DEFINES+=DISPLAY_UDF DISABLE_RTC NDEBUG

LIBS=oscserver osc

SRCDIR=firmware lib

include ../firmware-template-h3/Rules.mk

prerequisites:
