#
PLATFORM = ORANGE_PI
#
DEFINES = E131_BRIDGE_MULTI DISPLAY_UDF RDMNET_LLRP_ONLY DISABLE_RTC NDEBUG
#
LIBS = rdmnet rdm rdmsensor rdmsubdevice artnet
#
SRCDIR = firmware lib

include ../h3-firmware-template/Rules.mk

prerequisites:
	./generate_sofware_version_id.sh
