#
PLATFORM = ORANGE_PI
#
DEFINES = E131_BRIDGE_MULTI RDMNET_LLRP_ONLY DISPLAY_UDF NDEBUG
#
LIBS = rdmnet rdm rdmsensor rdmsubdevice
#
SRCDIR = firmware lib

include ../h3-firmware-template/Rules.mk

prerequisites:
	./generate_sofware_version_id.sh