#
PLATFORM = ORANGE_PI
#
DEFINES = NODE_E131_MULTI DISPLAY_UDF NODE_RDMNET_LLRP_ONLY DISABLE_RTC NDEBUG
#
LIBS = rdmnet rdm rdmsensor rdmsubdevice
#
SRCDIR = firmware lib

include ../h3-firmware-template/Rules.mk

prerequisites:
	./generate_sofware_version_id.sh
