#
DEFINES = NDEBUG
#
EXTRA_INCLUDES = ../lib-display/include ../lib-properties/include ../lib-network/include ../lib-hal/include ../lib-artnet/include ../lib-e131/include ../lib-lightset/include
#
include ../h3-firmware-template/lib/Rules.mk
