DEFINES=NDEBUG
EXTRA_INCLUDES = ../lib-display/include ../lib-properties/include ../lib-network/include ../lib-hal/include ../lib-lightset/include

include Rules.mk
include ../firmware-template-h3/lib/Rules.mk
