
DEFINES=NO_EMAC RDM_RESPONDER OUTPUT_DMX_STEPPER NDEBUG

LIBS=dmxreceiver rdmresponder dmx l6470dmx l6470 tlc59711dmx tlc59711

SRCDIR=firmware lib

include ../firmware-template-h3/Rules.mk

prerequisites:
	./generate_sofware_version_id.sh
