DEFINES=NO_EMAC RDM_RESPONDER
DEFINES+=OUTPUT_DMX_TLC59711 OUTPUT_DMX_STEPPER
DEFINES+=DISPLAY_UDF
DEFINES+=NDEBUG

LIBS=dmxreceiver rdmresponder dmx l6470dmx l6470 tlc59711dmx tlc59711

SRCDIR=firmware lib

include ../firmware-template-h3/Rules.mk

prerequisites:
	./generate_sofware_version_id.sh
