#
DEFINES = NDEBUG
#
EXTRA_INCLUDES = ../lib-rdm/include ../lib-properties/include ../lib-bob/include ../lib-i2c/include ../lib-hal/include ../lib-utils/include
#
include ../h3-firmware-template/lib/Rules.mk