PLATFORM=ORANGE_PI_ONE
#
DEFINES = CONSOLE_FB
#
LIBS = dmxmonitor
#
SRCDIR = firmware lib lib/ImSoft

LVGL_DIR = lib/lvgl

include ../h3-firmware-template/Rules.mk lib/ImSoft/component.mk



prerequisites: