#
# Makefile
#

CIRCLEHOME = ../Circle

INCLUDE	+= -I ./include
INCLUDE	+= -I ../lib-bcm2835_circle/include
INCLUDE	+= -I ../include

#OBJS  = src/tlc59711.o

EXTRACLEAN = src/*.o

libtlc59711.a: $(OBJS)
	rm -f $@
	$(AR) cr $@ $(OBJS)
	$(PREFIX)objdump -D libtlc59711.a | $(PREFIX)c++filt > libtlc59711.lst

include $(CIRCLEHOME)/Rules.mk