DEFINES =NODE_E131 LIGHTSET_PORTS=4 
DEFINES+=CONFIG_PIXELDMX_MAX_PORTS=1
DEFINES+=ESP8266 
DEFINES+=CONSOLE_FB 
DEFINES+=ENABLE_MMU 
DEFINES+=DISABLE_RTC 
DEFINES+=NDEBUG
 
LIBS=e131 dmxsend dmx ws28xxdmx ws28xx dmxmonitor lightset display

SRCDIR=firmware

include ../firmware-template-bcm/Rules.mk

prerequisites: