#
DEFINES = RDMNET_LLRP_ONLY DISPLAY_UDF DISABLE_RTC NDEBUG
#
LIBS = rdmnet rdm rdmsensor rdmsubdevice
#
SRCDIR = firmware lib

include ../h3-firmware-template/Rules.mk

prerequisites:
	./generate_sofware_version_id.sh
