#PLATFORM=

DEFINES =NODE_RDMNET_LLRP_ONLY

DEFINES+=DISPLAY_UDF 
DEFINES+=ENABLE_SSD1311 

DEFINES+=ENABLE_HTTPD ENABLE_CONTENT

DEFINES+=ENET_LINK_CHECK_REG_POLL

DEFINES+=NDEBUG

LIBS=

SRCDIR=firmware lib

include ../firmware-template-h3/Rules.mk
prerequisites:
	@echo "constexpr uint32_t DEVICE_SOFTWARE_VERSION_ID="$(shell date "+%s")";" > ./include/software_version_id.h

