DEFINES=NODE_RDMNET_LLRP_ONLY DISPLAY_UDF ENABLE_SSD1311 NDEBUG
LIBS=rdmnet rdm rdmsensor rdmsubdevice
SRCDIR=firmware lib

include ../firmware-template-h3/Rules.mk
prerequisites:
	./generate_sofware_version_id.sh
