PLATFORM=ORANGE_PI

DEFINES=NODE_SHOWFILE DISPLAY_UDF SD_WRITE_SUPPORT SD_EXFAT_SUPPORT NODE_RDMNET_LLRP_ONLY DISABLE_RTC NDEBUG

SRCDIR=firmware lib

LIBS=

include ../firmware-template-h3/Rules.mk

prerequisites:
	./generate_sofware_version_id.sh