PLATFORM = ORANGE_PI
#
DEFINES = SHOWFILE DISPLAY_UDF SD_WRITE_SUPPORT SD_EXFAT_SUPPORT RDMNET_LLRP_ONLY DISABLE_RTC NDEBUG
#
LIBS = showfile osc rdmnet rdm rdmsensor rdmsubdevice
#
SRCDIR = firmware lib

include ../h3-firmware-template/Rules.mk

prerequisites:
	./generate_sofware_version_id.sh