#
# Makefile
#

CIRCLEHOME = ../Circle

INCLUDE	+= -I ./include
INCLUDE	+= -I ../lib-properties/include -I ../lib-lightset/include
INCLUDE	+= -I ../include

OBJS	= src/dmxparams.o src/dmxsendprint.o src/circle/dmxsend.o

EXTRACLEAN = src/circle/*.o src/*.o 

libdmxsend.a: $(OBJS)
	rm -f $@
	$(AR) cr $@ $(OBJS)
	$(PREFIX)objdump -D libdmxsend.a | $(PREFIX)c++filt > libdmxsend.lst

include $(CIRCLEHOME)/Rules.mk

