#
DEFINES = ARTNET_NODE ESP8266 ENABLE_MMU NDEBUG
#
LIBS = display rdmdiscovery artnet dmxsend ws28xxdmx ws28xx dmxmonitor dmx rdmdiscovery rdm lightset
#
SRCDIR = firmware lib

include ../firmware-template/Rules.mk

prerequisites: