#
DEFINES = ARTNET_NODE ESP8266 ENABLE_MMU DISABLE_RTC NDEBUG
#
LIBS = display rdmdiscovery artnet dmxsend ws28xxdmx ws28xx dmxmonitor rdmdiscovery rdm dmx lightset
#
SRCDIR = firmware lib

include ../firmware-template/Rules.mk

prerequisites: