#
DEFINES = ARTNET_NODE ESP8266 ENABLE_MMU NO_EMAC NDEBUG
#
LIBS = display rdmdiscovery artnet dmxsend ws28xxdmx ws28xx dmx rdm lightset ledblink
#
SRCDIR = firmware lib

include ../h3-firmware-template/Rules.mk

prerequisites:
