#
DEFINES = ESP8266 ENABLE_MMU NDEBUG
#
LIBS = display rdmdiscovery artnet dmxsend ws28xxdmx ws28xx dmxmonitor monitor dmx rdmdiscovery rdm lightset ledblink 
#
SRCDIR = firmware lib

include ../firmware-template/Rules.mk

prerequisites: