#
DEFINES = RASPPI #NDEBUG
#
EXTRA_INCLUDES = ../lib-hal/include ../lib-ledblink/include  ../lib-spiflash/include ../lib-display/include ../lib-properties/include
#
include ../linux-template/lib/Rules.mk