PLATFORM=ORANGE_PI_ONE

DEFINES=NODE_OSC_SERVER ENABLE_SPIFLASH CONSOLE_FB NDEBUG
DEFINES+=ENABLE_HTTPD

LIBS=oscserver osc dmxmonitor

SRCDIR=firmware lib

include ../firmware-template-h3/Rules.mk

prerequisites:
