DEFINES=NODE_OSC_SERVER OUTPUT_DMX_MONITOR DISPLAY_UDF ENABLE_SPIFLASH #NDEBUG
LIBS=oscserver osc dmxmonitor lightset artnet displayudf
SRCDIR=src lib

include ../firmware-template-linux/Rules.mk

prerequisites: