#
DEFINES = NODE_OSC_SERVER OUTPUT_DMX_MONITOR ENABLE_SPIFLASH NDEBUG
#
LIBS = oscserver osc dmxmonitor lightset artnet artnet4 e131
#
SRCDIR = src lib

include ../firmware-template-linux/Rules.mk

prerequisites: