#
# Makefile
#

CIRCLEHOME = ../Circle

INCLUDE	+= -I ./include

OBJS  = src/bcm2835.o 

EXTRACLEAN = src/*.o

libbcm2835.a: $(OBJS)
	rm -f $@
	$(AR) cr $@ $(OBJS)
	$(PREFIX)objdump -D libbcm2835.a | $(PREFIX)c++filt > libbcm2835.lst

include $(CIRCLEHOME)/Rules.mk