PLATFORM=ORANGE_PI

DEFINES=NODE_OSC_CLIENT ENABLE_SPIFLASH DISABLE_RTC NDEBUG
DEFINES+=ENABLE_HTTPD

LIBS=oscclient osc

SRCDIR=firmware lib

include ../firmware-template-h3/Rules.mk

prerequisites:
