PLATFORM=ORANGE_PI

DEFINES=NODE_ARTNET
DEFINES+=NODE_RDMNET_LLRP_ONLY
DEFINES+=OUTPUT_DMX_SERIAL SD_WRITE_SUPPORT SD_EXFAT_SUPPORT 
DEFINES+=DISPLAY_UDF DISABLE_RTC NDEBUG

LIBS=dmxserial rdmnet rdm rdmsensor rdmsubdevice

SRCDIR=firmware lib

include ../firmware-template-h3/Rules.mk

prerequisites:
	./generate_sofware_version_id.sh