DEFINES=
EXTRA_INCLUDES=../lib-dmx/include ../lib-dmxreceiver/include ../lib-rdm/include ../lib-rdmsensor/include ../lib-rdmsubdevice/include ../lib-artnet/include ../lib-lightset/include

include ../linux-template/lib/Rules.mk
