#
DEFINES = NDEBUG
#
EXTRA_INCLUDES = ../lib-rdm/include ../lib-rdmsensor/include ../lib-rdmsubdevice/include ../lib-dmxreceiver/include ../lib-dmx/include ../lib-artnet/include ../lib-lightset/include ../lib-utils/include
#
include ../firmware-template/lib/Rules.mk