#
DEFINES = NDEBUG
#
EXTRA_INCLUDES = ../lib-hal/include../lib-monitor/include ../lib-dmx/include ../lib-rdm/include ../lib-properties/include ../lib-usb/include
#
include ../h3-firmware-template/lib/Rules.mk