DEFINES=UPDATE_CONFIG_FILE NDEBUG

EXTRA_SRCDIR=src/rpi/properties src/hdmi

EXTRA_INCLUDES=../lib-hal/include ../lib-hal/ff12c ../lib-properties/include ../lib-dmx/include ../lib-rdm/include ../lib-usb/include

include ../firmware-template-bcm/lib/Rules.mk