#
DEFINES = UPDATE_CONFIG_FILE NDEBUG
#
EXTRA_SRCDIR = src/rpi/properties
#
EXTRA_INCLUDES = ../lib-hal/include ../lib-hal/ff12c ../lib-monitor/include ../lib-dmx/include ../lib-rdm/include ../lib-usb/include
#
include ../firmware-template/lib/Rules.mk