#
DEFINES = NDEBUG
#
EXTRA_INCLUDES = ../lib-hal/include ../lib-monitor/include ../lib-dmx/include ../lib-rdm/include ../lib-properties/include ../lib-usb/include ../lib-console/include ../lib-ff12c/src
#
include ../h3-firmware-template/lib/Rules.mk