DEFINES =NDEBUG

EXTRA_INCLUDES=../lib-h3/CMSIS/Include

EXTRA_SRCDIR=

ifneq ($(MAKE_FLAGS),)
else
	DEFINES+=CONFIG_LTC_USE_DAC
	EXTRA_SRCDIR+=src/displayrgb src/displayrgb/panel src/displayrgb/ws28xx
	EXTRA_INCLUDES+=../lib-rgbpanel/include ../lib-ws28xxdisplay/include ../lib-ws28xx/include
endif

include Rules.mk
include ../firmware-template-h3/lib/Rules.mk

