DEFINES =LIGHTSET_PORTS=1
DEFINES+=NDEBUG

EXTRA_INCLUDES =../lib-display/include ../lib-artnet/include ../lib-tcnet/include  ../lib-midi/include ../lib-ws28xxdisplay/include ../lib-ws28xx/include ../lib-rgbpanel/include ../lib-device/include ../lib-hal/include ../lib-network/include ../lib-properties/include ../lib-lightset/include
EXTRA_INCLUDES+=../lib-h3/CMSIS/Include

EXTRA_SRCDIR=src/arm

include ../firmware-template-h3/lib/Rules.mk

