#
DEFINES = ARTNET_NODE EMAC ENABLE_SPIFLASH NDEBUG #DO_NOT_USE_UART0
#
LIBS = rdmdiscovery artnet dmxsend ws28xxdmx ws28xx monitor dmx rdm lightset ledblink
#
SRCDIR = firmware lib

include ../h3-firmware-template/Rules.mk

prerequisites:
