DEFINES=NODE_ARTNET_MULTI
DEFINES+=OUTPUT_DMX_SEND_MULTI
DEFINES+=DISPLAY_UDF ENABLE_SSD1311 DISABLE_RTC NDEBUG

LIBS=rdmdiscovery rdm

SRCDIR=firmware lib

include ../firmware-template-h3/Rules.mk

prerequisites:
