#
DEFINES = NDEBUG
#
EXTRA_INCLUDES = ../lib-pca9685/include ../lib-pca9685dmx/include ../lib-tlc59711/include ../lib-tlc59711dmx/include ../lib-lightset/include ../lib-properties/include ../lib-utils/include
#
include ../firmware-template/lib/Rules.mk
	