DEFINES=NDEBUG

EXTRA_INCLUDES=

EXTRA_SRCDIR=rtc/i2c src/h3/sdcard

ifneq (,$(findstring DEBUG_EMAC,$(MAKE_FLAGS)))
	EXTRA_SRCDIR+=debug/emac/h3
else
	EXTRA_SRCDIR+=debug/emac/h3
endif

include Rules.mk
include ../firmware-template-h3/lib/Rules.mk
