#
# Makefile
#

CIRCLEHOME = ../Circle

INCLUDE	+= -I ./include
INCLUDE	+= -I ../include

OBJS	= src/hardware.o src/circle/hardwarecircle.o 

EXTRACLEAN = src/circle/*.o src/*.o

libhal.a: $(OBJS)
	rm -f $@
	$(AR) cr $@ $(OBJS)
	$(PREFIX)objdump -D libhal.a | $(PREFIX)c++filt > libhal.lst

include $(CIRCLEHOME)/Rules.mk
