#DEFINES=NDEBUG

EXTRA_INCLUDES=src/linux/minimum
EXTRA_SRCDIR=src/linux/minimum
EXTRA_SRCDIR+=superloop

EXTRA_SRCDIR+=debug

ifneq ($(MAKE_FLAGS),)
	ifeq (,$(findstring DISABLE_RTC,$(MAKE_FLAGS)))
		EXTRA_SRCDIR+=rtc rtc/i2c
	endif
	ifneq (,$(findstring LINUX_HAVE_I2C,$(MAKE_FLAGS)))
		EXTRA_SRCDIR+=src/linux/i2c
	endif
	ifneq (,$(findstring DEBUG_I2C,$(MAKE_FLAGS)))
			EXTRA_SRCDIR+=debug/i2c
			EXTRA_INCLUDES+=debug/i2c
	endif
endif

include ../firmware-template-linux/lib/Rules.mk
