DEFINES=#NDEBUG

EXTRA_INCLUDES=../lib-artnet/include ../lib-e131/include ../lib-properties/include ../lib-spiflashstore/include ../lib-lightset/include ../lib-network/include

include ../firmware-template-linux/lib/Rules.mk
