#
DEFINES = NDEBUG
#
EXTRA_INCLUDES = ../lib-dmx/include ../lib-rdm/include ../lib-utils/include ../lib-artnet/include ../lib-lightset/include ../lib-ledblink/include ../lib-hal/include
#
include ../firmware-template/lib/Rules.mk