#DEFINES=NDEBUG

EXTRA_INCLUDES=../lib-rdm/include ../lib-lightset/include ../lib-properties/include ../lib-device/include

ifneq ($(MAKE_FLAGS),)
	ifneq (,$(findstring RASPI,$(MAKE_FLAGS)))
		EXTRA_SRCDIR += src/spi
	endif
endif
#
include ../firmware-template-linux/lib/Rules.mk
