#
# Makefile
#

CIRCLEHOME = ../Circle

INCLUDE	+= -I ./include
INCLUDE	+= -I ../lib-rdm/include
INCLUDE	+= -I ../lib-properties/include
INCLUDE	+= -I ../include

OBJS  = src/rdmsubdevice.o src/rdmsubdevices.o
OBJS += src/rdmsubdevicedummy.o

EXTRACLEAN = src/*.o

librdmsubdevice.a: $(OBJS)
	rm -f $@
	$(AR) cr $@ $(OBJS)
	$(PREFIX)objdump -D librdmsubdevice.a | $(PREFIX)c++filt > librdmsubdevice.lst

include $(CIRCLEHOME)/Rules.mk
