ifneq ($(MAKE_FLAGS),)
	ifeq ($(findstring ESP8266,$(MAKE_FLAGS)), ESP8266)
		EXTRA_SRCDIR+=src/esp8266	
	endif
else
	DEFINES+=OUTPUT_HAVE_STYLESWITCH
	DEFINES+=LIGHTSET_HAVE_RUN
	DEFINES+=ESP8266
	EXTRA_SRCDIR+=src/esp8266	
endif