PLATFORM=ORANGE_PI

DEFINES=NO_EMAC RDM_RESPONDER OUTPUT_DMX_PIXEL NDEBUG

LIBS=dmxreceiver rdmresponder dmx 

SRCDIR=firmware lib

include ../firmware-template-h3/Rules.mk

prerequisites:
	./generate_sofware_version_id.sh