PLATFORM = ORANGE_PI
#
DEFINES = NO_EMAC RDM_RESPONDER OUTPUT_PIXEL NDEBUG
#
LIBS = dmxreceiver rdmresponder dmx 
#
SRCDIR = firmware lib

include ../h3-firmware-template/Rules.mk

prerequisites:
	./generate_sofware_version_id.sh