PLATFORM=ORANGE_PI

DEFINES=RDM_RESPONDER 
#DEFINES+=NO_EMAC 
DEFINES+=OUTPUT_DMX_PIXEL 
DEFINES+=DISPLAY_UDF
#DEFINES+=NDEBUG

SRCDIR=firmware lib

LIBS=

include ../firmware-template-h3/Rules.mk

prerequisites:
	./generate_sofware_version_id.sh