$(info "Board.mk")

BOARD_DEFS :=-DH3 -D$(PLATFORM)
BOARD_DEFS +=-DENABLE_TFTP_SERVER
BOARD_DEFS +=-DCONFIG_MDNS_DOMAIN_REVERSE
BOARD_DEFS +=-DISABLE_INTERNAL_RTC
BOARD_DEFS +=-DHTTPD_CONTENT_SIZE=4096
BOARD_DEFS +=-DCONFIG_EMAC_HASH_MULTICAST_FILTER

$(info $$BOARD_DEFS [${BOARD_DEFS}])