DEFINES=NDEBUG

EXTRA_INCLUDES=../lib-l6470/include ../lib-lightset/include ../lib-properties/include ../lib-hal/include
EXTRA_INCLUDES+=../lib-display/include

include ../firmware-template-linux/lib/Rules.mk
