#PLATFORM = ORANGE_PI_ONE
#
DEFINES = NDEBUG
#
EXTRA_INCLUDES = ../lib-l6470/include ../lib-lightset/include ../lib-properties/include ../lib-hal/include
#
include ../h3-firmware-template/lib/Rules.mk
	
