PLATFORM=ORANGE_PI

DEFINES=NODE_E131 E131_PORTS=5
DEFINES+=NODE_RDMNET_LLRP_ONLY
DEFINES+=OUTPUT_DMX_PIXEL OUTPUT_DMX_SEND
DEFINES+=DISPLAY_UDF DISABLE_RTC ENABLE_SSD1311 NDEBUG

LIBS=rdmnet rdm rdmsensor rdmsubdevice

SRCDIR=firmware lib

include ../firmware-template-h3/Rules.mk

prerequisites:
	./generate_sofware_version_id.sh