#
DEFINES = NDEBUG
#
EXTRA_INCLUDES = ../lib-display/include ../lib-properties/include ../lib-h3/include ../lib-hal/include ../lib-network/include ../lib-spiflashinstall/include ../lib-spiflashstore/include ../lib-tftpdeamon/include ../lib-rdm/include ../lib-ws28xxdmx/include ../lib-artnet/include ../lib-artnet4/include ../lib-e131/include ../lib-network/include ../lib-dmxsend/include ../lib-dmx/include ../lib-ws28xxdmx/include ../lib-ws28xx/include ../lib-tlc59711dmx/include ../lib-tlc59711/include ../lib-ltc/include ../lib-tcnet/include ../lib-midi/include ../lib-oscserver/include ../lib-oscclient/include ../lib-widget/include ../lib-lightset/include ../lib-ledblink/include
#
include ../h3-firmware-template/lib/Rules.mk
