DEFINES =ENABLE_TFTP_SERVER
DEFINES+=NDEBUG

EXTRA_SRCDIR=
EXTRA_INCLUDES=

ifneq ($(MAKE_FLAGS),)
else
	DEFINES+=LTC_READER
	EXTRA_SRCDIR+=src/shell src/uart
endif

EXTRA_SRCDIR+=src/tftp

include Rules.mk
include ../firmware-template-h3/lib/Rules.mk
