#
DEFINES = RASPPI ARTNET_NODE_MULTI E131_BRIDGE_MULTI DMXSEND_MULTI PIXEL_MULTI LTC_READER OSC_SERVER OSC_CLIENT DISPLAY_UDF DISPLAY_NEXTION STEPPER RDM_RESPONDER #NDEBUG
#
EXTRA_INCLUDES = ../lib-display/include ../lib-properties/include ../lib-bcm2835/include ../lib-hal/include ../lib-network/include  ../lib-displayudf/include ../lib-display/include ../lib-spiflashinstall/include ../lib-spiflashstore/include ../lib-tftpdeamon/include ../lib-rdm/include ../lib-ws28xxdmx/include ../lib-artnet/include ../lib-artnet4/include ../lib-e131/include ../lib-network/include ../lib-dmxsend/include ../lib-dmx/include ../lib-ws28xxdmx/include ../lib-ws28xx/include ../lib-tlc59711dmx/include ../lib-tlc59711/include ../lib-ltc/include ../lib-tcnet/include ../lib-midi/include ../lib-oscserver/include ../lib-oscclient/include ../lib-widget/include ../lib-rdm/include ../lib-nextion/include ../lib-l6470dmx/include ../lib-l6470/include ../lib-lightset/include ../lib-ledblink/include ../lib-bob/include
#
include ../linux-template/lib/Rules.mk
