EXTRA_INCLUDES =../lib-flash/include ../lib-flashcode/include
EXTRA_INCLUDES+=../lib-flashcodeinstall/include ../lib-configstore/include
EXTRA_INCLUDES+=../lib-device/include
EXTRA_INCLUDES+=../lib-displayudf/include ../lib-display/include
EXTRA_INCLUDES+=../lib-properties/include ../lib-hal/include ../lib-network/include
EXTRA_INCLUDES+=../lib-dmxmonitor/include ../lib-dmxreceiver/include ../lib-dmxsend/include ../lib-dmxserial/include ../lib-dmx/include
EXTRA_INCLUDES+=../lib-rdm/include ../lib-rdmresponder/include
EXTRA_INCLUDES+=../lib-artnet/include ../lib-artnet4/include ../lib-rdmdiscovery/include
EXTRA_INCLUDES+=../lib-e131/include ../lib-ws28xxdmx/include ../lib-ws28xx/include ../lib-tlc59711dmx/include ../lib-tlc59711/include ../lib-ltc/include ../lib-tcnet/include ../lib-midi/include ../lib-oscserver/include ../lib-oscclient/include ../lib-widget/include ../lib-l6470dmx/include ../lib-l6470/include ../lib-rdmsensor/include ../lib-rdmsubdevice/include ../lib-showfile/include ../lib-gps/include ../lib-rgbpanel/include ../lib-ddp/include ../lib-lightset/include
EXTRA_INCLUDES+=../lib-node/include
