#
# Makefile
#

CIRCLEHOME = ../Circle

INCLUDE	+= -I ./include
INCLUDE	+= -I ../lib-pca9685/include
INCLUDE	+= -I ../lib-lightset/include -I ../lib-properties/include
INCLUDE	+= -I ../include

OBJS  = src/params.o
OBJS += src/pwmleddmx.o src/pwmledparams.o
OBJS += src/servodmx.o src/servoparams.o 

EXTRACLEAN = src/*.o

libpca9685dmx.a: $(OBJS)
	rm -f $@
	$(AR) cr $@ $(OBJS)
	$(PREFIX)objdump -D libpca9685dmx.a | $(PREFIX)c++filt > libpca9685dmx.lst

include $(CIRCLEHOME)/Rules.mk