#
DEFINES = E131_BRIDGE ARM_ALLOW_MULTI_CORE DO_NOT_USE_EXTERNAL_LED DISABLE_RTC
#
# Needed for shell
LIBS = gps
#
SRCDIR = firmware lib lib/h3

include ../h3-firmware-template/Rules.mk

prerequisites:
