DEFINES=NDEBUG

EXTRA_INCLUDES=

ifneq ($(MAKE_FLAGS),)
	ifeq ($(findstring ARTNET_HAVE_FAILSAFE_RECORD,$(MAKE_FLAGS)), ARTNET_HAVE_FAILSAFE_RECORD)
		EXTRA_SRCDIR=src/node/failsafe/spi
	endif
else
	EXTRA_SRCDIR=src/node/failsafe/spi src/node/failsafe/rom
endif

include Rules.mk
include ../firmware-template-h3/lib/Rules.mk
