#
DEFINES = NDEBUG
#
EXTRA_INCLUDES = ../lib-lightset/include ../lib-ledblink/include ../lib-properties/include ../lib-hal/include ../lib-network/include ../lib-utils/include
#
include ../firmware-template/lib/Rules.mk