#
# Makefile
#

CIRCLEHOME = ../Circle

INCLUDE	+= -I ../lib-artnet/include -I ../lib-lightset/include -I ../lib-ledblink/include -I ../lib-network/include

OBJS	= src/artnetnode.o src/artnettimecode.o src/artnettimesync.o

EXTRACLEAN = src/*.o

libartnet.a: $(OBJS)
	rm -f $@
	$(AR) cr $@ $(OBJS)
	$(PREFIX)objdump -D libartnet.a | $(PREFIX)c++filt > libartnet.lst

include $(CIRCLEHOME)/Rules.mk
