#
# Makefile
#

CIRCLEHOME = ../Circle

INCLUDE	+= -I ./include
INCLUDE	+= -I ../lib-properties/include
INCLUDE	+= -I ../lib-lightset/include -I ../lib-ledblink/include
INCLUDE	+= -I ../lib-hal/include -I ../lib-network/include
INCLUDE	+= -I ../include

OBJS	= src/artnetnode.o src/artnetparams.o src/artnetnodeprint.o

EXTRACLEAN = src/*.o

libartnet.a: $(OBJS)
	rm -f $@
	$(AR) cr $@ $(OBJS)
	$(PREFIX)objdump -D libartnet.a | $(PREFIX)c++filt > libartnet.lst

include $(CIRCLEHOME)/Rules.mk
