#
DEFINES = ESP8266 LTC_READER MIDI_INTERFACE_UART MIDI_INTERFACE_SPI ENABLE_MMU NDEBUG
#
LIBS = midi artnet lightset ledblink network
#
SRCDIR = firmware lib

include ../firmware-template/Rules.mk

prerequisites: