#
DEFINES = NDEBUG
#
EXTRA_INCLUDES = ../lib-display/include ../lib-displayudf/include ../lib-properties/include ../lib-remoteconfig/include ../lib-spiflashstore/include ../lib-artnet/include ../lib-artnet4/include ../lib-e131/include ../lib-ws28xxdmx/include ../lib-ws28xx/include ../lib-tlc59711dmx/include ../lib-tlc59711/include ../lib-lightset/include ../lib-network/include ../lib-bob/include ../lib-i2c/include ../lib-tftpdeamon/include 
#
include ../h3-firmware-template/lib/Rules.mk
	