PLATFORM = ORANGE_PI
#
DEFINES = RDM_CONTROLLER NO_EMAC ENABLE_SPIFLASH DO_NOT_USE_EXTERNAL_LED NDEBUG
#
LIBS = widget rdm dmx usb
#
SRCDIR = firmware

include ../h3-firmware-template/Rules.mk

prerequisites:
