#
DEFINES = NO_EMAC RDM_CONTROLLER ENABLE_SPIFLASH DO_NOT_USE_EXTERNAL_LED NDEBUG
#
LIBS = widget rdm dmx usb
#
SRCDIR = firmware lib
#
EXTRA_INCLUDES = 

include ../h3-firmware-template/Rules.mk

prerequisites:
