PLATFORM=ORANGE_PI

DEFINES=RDM_CONTROLLER NO_EMAC ENABLE_SPIFLASH DO_NOT_USE_EXTERNAL_LED DISABLE_RTC NDEBUG

LIBS=widget rdm dmx usb

SRCDIR=firmware

include ../firmware-template-h3/Rules.mk

prerequisites:
