#
DEFINES = LTC_READER RDMNET_LLRP_ONLY NDEBUG
#
LIBS = ltc tcnet midi input osc ws28xxdisplay ws28xx rdmnet rdm rdmsensor rdmsubdevice
#
SRCDIR = firmware lib

include ../h3-firmware-template/Rules.mk

prerequisites:
	./generate_sofware_version_id.sh	
