#
DEFINES = LTC_READER RDMNET_LLRP_ONLY ARM_ALLOW_MULTI_CORE NDEBUG #ENABLE_SHELL
#
LIBS = ltc tcnet artnethandlers midi input osc ws28xxdisplay ws28xx rgbpanel rdmnet rdm rdmsensor rdmsubdevice gps
#
SRCDIR = firmware lib

include ../h3-firmware-template/Rules.mk

prerequisites:
	./generate_sofware_version_id.sh	
