#
EXTRA_INCLUDES = ../lib-lightset/include ../lib-hal/include ../lib-properties/include ../lib-utils/include ../lib-uuid/include ../lib-network/include ../lib-esp8266/include
#

include ../firmware-template/lib/Rules.mk