#
# Makefile
#

CIRCLEHOME = ../Circle

INCLUDE	+= -I ./include
INCLUDE	+= -I ../lib-bcm2835_circle/include
INCLUDE	+= -I ../include

OBJS  = src/pca9685.o
OBJS += src/pca9685pwmled.o src/pca9685servo.o 

EXTRACLEAN = src/*.o

libpca9685.a: $(OBJS)
	rm -f $@
	$(AR) cr $@ $(OBJS)
	$(PREFIX)objdump -D libpca9685.a | $(PREFIX)c++filt > libpca9685.lst

include $(CIRCLEHOME)/Rules.mk