#
DEFINES = NDEBUG
#
EXTRA_INCLUDES = ../lib-rdm/include ../lib-rdmsensor/include ../lib-rdmsubdevice/include ../lib-e131/include ../lib-network/include ../lib-lightset/include
#
include ../h3-firmware-template/lib/Rules.mk
