#
DEFINES = ESP8266 ENABLE_MMU NDEBUG
#
LIBS = e131 uuid dmxsend dmx ws28xxdmx ws28xx dmxmonitor monitor lightset ledblink display
#
SRCDIR = firmware

include ../firmware-template/Rules.mk

prerequisites: