#
DEFINES = ESP8266 ENABLE_MMU DISABLE_RTC NDEBUG
#
LIBS = e131 uuid dmxsend dmx ws28xxdmx ws28xx dmxmonitor lightset display
#
SRCDIR = firmware

include ../firmware-template/Rules.mk

prerequisites: