#
# Makefile
#

CIRCLEHOME = ../Circle

INCLUDE	+= -I ../Circle/addon/fatfs
INCLUDE	+= -I ../include

OBJS	= src/file.o src/log.o src/circle/fgets.o src/circle/printf.o src/circle/sprintf.o src/circle/snprintf.o

EXTRACLEAN = src/circle/*.o src/*.o

libutils.a: $(OBJS)
	rm -f $@
	$(AR) cr $@ $(OBJS)
	$(PREFIX)objdump -D libutils.a | $(PREFIX)c++filt > libutils.lst

include $(CIRCLEHOME)/Rules.mk
