#
# Makefile
#

CIRCLEHOME = ../Circle

INCLUDE	+= -I ./include
INCLUDE	+= -I ../lib-i2c/include
INCLUDE	+= -I ../include

OBJS	= src/bh1750.o src/htu21d.o src/ina219.o src/mcp9808.o src/si7021.o

EXTRACLEAN = src/*.o

libbob.a: $(OBJS)
	rm -f $@
	$(AR) cr $@ $(OBJS)
	$(PREFIX)objdump -D libbob.a | $(PREFIX)c++filt > libbob.lst

include $(CIRCLEHOME)/Rules.mk
