#
DEFINES = SD_WRITE_SUPPORT CACHE_ENABLED NDEBUG #EMMC_DEBUG SD_DEBUG
#
EXTRA_INCLUDES = ../lib-bcm2835/include ../lib-hal/include ../lib-ff12c/src ../lib-utils/include
#
include ../firmware-template/lib/Rules.mk		