#
EXTRA_INCLUDES = ../lib-ws28xx/include ../lib-lightset/include ../lib-bcm2835/include ../lib-monitor/include ../lib-properties/include ../lib-utils/include
#
include ../firmware-template/lib/Rules.mk