#
DEFINES = NDEBUG
#
EXTRA_INCLUDES = ../lib-ws28xx/include ../lib-lightset/include ../lib-monitor/include ../lib-properties/include ../lib-utils/include
#
include ../h3-firmware-template/lib/Rules.mk
