DEFINES=USE_SPI_DMA
DEFINES+=#NDEBUG
 #DEFINES+=PARAMS_INLCUDE_ALL

EXTRA_INCLUDES=../lib-ws28xx/include ../lib-lightset/include ../lib-properties/include 

include ../firmware-template-h3/lib/Rules.mk
