#
PLATFORM = ORANGE_PI
#
DEFINES = NODE_ARTNET OUTPUT_DMXSEND DISPLAY_UDF DISABLE_RTC NDEBUG
#
LIBS = rdmdiscovery rdm
#
SRCDIR = firmware lib

include ../h3-firmware-template/Rules.mk

prerequisites:
