#
DEFINES = ARTNET_NODE EMAC NDEBUG
#
LIBS = rdmdiscovery artnet dmxsend ws28xxdmx ws28xx monitor dmx rdm lightset ledblink
#
SRCDIR = firmware lib

include ../h3-firmware-template/Rules.mk

prerequisites:
