PLATFORM=ORANGE_PI

DEFINES=NODE_ARTNET
DEFINES+=OUTPUT_DMX_SEND 
DEFINES+=DISPLAY_UDF DISABLE_RTC NDEBUG

LIBS=rdmdiscovery rdm

SRCDIR=firmware lib

include ../firmware-template-h3/Rules.mk

prerequisites:
