#
# Makefile
#

CIRCLEHOME = ../Circle

INCLUDE	+= -I ./include 
INCLUDE	+= -I ../lib-network/include -I ../lib-properties/include
INCLUDE	+= -I ../include

OBJS = src/osc.o src/oscaddress.o src/oscblob.o src/oscmessage.o src/oscsend.o src/oscstring.o src/oscutil.o src/pattern_match.o src/oscparams.o

EXTRACLEAN = src/*.o

libosc.a: $(OBJS)
	rm -f $@
	$(AR) cr $@ $(OBJS)
	$(PREFIX)objdump -D libosc.a | $(PREFIX)c++filt > libosc.lst

include $(CIRCLEHOME)/Rules.mk
