#
DEFINES = NDEBUG
#
EXTRA_INCLUDES = ../lib-tlc59711/include ../lib-lightset/include ../lib-properties/include ../lib-bcm2835/include ../lib-utils/include
#
include ../firmware-template/lib/Rules.mk
	