#
DEFINES = ESP8266 ENABLE_MMU DISABLE_RTC NDEBUG
#
LIBS = display oscserver osc dmxmonitor dmxsend ws28xxdmx ws28xx dmx lightset
#
SRCDIR = firmware lib

include ../firmware-template-bcm/Rules.mk

prerequisites:
