#
DEFINES = NODE_OSC_SERVER OUTPUT_DMXSEND OUTPUT_PIXEL ESP8266 DO_NOT_USE_EXTERNAL_LED NDEBUG
#
LIBS = oscserver osc
#
SRCDIR = firmware lib

include ../h3-firmware-template/Rules.mk

prerequisites:
