#
EXTRA_INCLUDES = ../lib-bob/include ../lib-hal/include ../lib-fb/include ../lib-properties/include ../lib-utils/include ../lib-bcm2835/include ../lib-lightset/include
#
include ../firmware-template/lib/Rules.mk