#
# Makefile
#

CIRCLEHOME = ../Circle

INCLUDE	+= -I ./include
INCLUDE	+= -I ../lib-properties/include -I ../lib-lightset/include
INCLUDE	+= -I ../include

OBJS	= src/dmxparams.o src/circle/dmxsender.o

EXTRACLEAN = src/dmxparams.o src/circle/*.o

libdmx.a: $(OBJS)
	rm -f $@
	$(AR) cr $@ $(OBJS)
	$(PREFIX)objdump -D libdmx.a | $(PREFIX)c++filt > libdmx.lst

include $(CIRCLEHOME)/Rules.mk