DEFINES=NDEBUG

EXTRA_INCLUDES=../lib-rdm/include ../lib-properties/include

ifneq ($(MAKE_FLAGS),)
	ifeq (,$(findstring OUTPUT_DMX_SEND_MULTI,$(MAKE_FLAGS)))
		EXTRA_SRCDIR+=src/h3/single
	else
		EXTRA_SRCDIR+=src/h3/multi
	endif
else
	DEFINES+=OUTPUT_DMX_SEND_MULTI
	EXTRA_SRCDIR+=src/h3/multi
#	DEFINES+=OUTPUT_DMX_SEND
#	EXTRA_SRCDIR+=src/h3/single
endif

include Rules.mk
include ../firmware-template-h3/lib/Rules.mk
