DEFINES=NDEBUG
DEFINES+=CMSIS_device_header=\"h3.h\"

EXTRA_SRCDIR=CMSIS/Core_A/Source arm device/mmc firmware

EXTRA_INCLUDES=CMSIS/Core_A/Include

ifneq ($(MAKE_FLAGS),)
	ifneq (,$(findstring CONSOLE_FB,$(MAKE_FLAGS)))
		EXTRA_SRCDIR+=device/fb
	endif
	ifneq (,$(findstring NO_EMAC,$(NO_EMAC)))
	else
		EXTRA_SRCDIR+=device/emac
	endif
else
	EXTRA_SRCDIR+=device/fb device/emac
endif

include ../firmware-template-h3/lib/Rules.mk
