#
DEFINES = ARTNET_NODE RDM_RESPONDER STEPPER PIXEL DISPLAY_UDF NDEBUG
#
LIBS = rdmresponder rdm rdmsensor rdmsubdevice l6470dmx l6470
#
SRCDIR = firmware lib

include ../h3-firmware-template/Rules.mk

prerequisites:
	./generate_sofware_version_id.sh