DEFINES=NODE_ARTNET
DEFINES+=RDM_RESPONDER OUTPUT_DMX_STEPPER DISPLAY_UDF NDEBUG

LIBS=rdmresponder l6470dmx l6470 tlc59711dmx tlc59711

SRCDIR=firmware lib

include ../h3-firmware-template/Rules.mk

prerequisites:
	./generate_sofware_version_id.sh