DEFINES=NDEBUG

EXTRA_INCLUDES =../lib-properties/include ../lib-network/include ../lib-hal/include
EXTRA_INCLUDES+=../lib-h3/CMSIS/Include

include Rules.mk
include ../firmware-template-h3/lib/Rules.mk

