#
DEFINES = NODE_E131 NODE_RDMNET_LLRP_ONLY OUTPUT_DMX_MONITOR ENABLE_SPIFLASH #NDEBUG
#
LIBS = e131 dmxmonitor lightset artnet artnet4
#
SRCDIR = src

include ../linux-template/Rules.mk

prerequisites:
