DEFINES=NODE_E131 NODE_RDMNET_LLRP_ONLY OUTPUT_DMX_MONITOR DISPLAY_UDF ENABLE_SPIFLASH #NDEBUG
LIBS=e131 dmxmonitor lightset artnet displayudf
SRCDIR=src

include ../firmware-template-linux/Rules.mk

prerequisites:
