#
# Makefile
#

CIRCLEHOME = ../Circle

INCLUDE	+= -I ./include 
INCLUDE	+= -I ../lib-osc/include
INCLUDE	+= -I ../lib-lightset/include -I ../lib-network/include -I ../lib-properties/include
INCLUDE	+= -I ../include

OBJS = src/oscserver.o 

EXTRACLEAN = src/*.o 

liboscserver.a: $(OBJS)
	rm -f $@
	$(AR) cr $@ $(OBJS)
	$(PREFIX)objdump -D liboscserver.a | $(PREFIX)c++filt > liboscserver.lst

include $(CIRCLEHOME)/Rules.mk
