#DEFINES=NDEBUG

EXTRA_INCLUDES=

ifneq ($(MAKE_FLAGS),)
	ifneq (,$(findstring CONFIG_FLASHROM_USE_I2C,$(MAKE_FLAGS)))
		EXTRA_SRCDIR+=src/i2c
	else
		EXTRA_SRCDIR+=src/file
	endif
else
	EXTRA_SRCDIR+=src/file
endif

include ../firmware-template-linux/lib/Rules.mk
